config/routes.rb
Rails.application.routes.draw do
  get "search/search"
  devise_for :users, controllers: {
                       registrations: "users/registrations",
                       omniauth_callbacks: "users/omniauth_callbacks",
                     }

  # Translation endpoint
  get "/translate", to: "translations#translate"

  # Routes for authenticated users
  authenticate :user do
    resources :collections, except: [:index, :show] do
      resources :items, except: [:show] do
        resources :comments, only: [:create, :destroy]
        resources :likes, only: [:create, :destroy]
      end

      # Add route for CSV export
      member do
        get "export_csv"
        delete "delete_custom_field/:custom_field_id", to: "collections#delete_custom_field", as: "delete_custom_field"
      end
    end

    # Move these actions inside the existing resources block
    # resources :collections, only: [:new, :create, :edit, :update, :destroy]

    resources :tickets, only: [:new, :create]

    # Profile route
    get "profile/:id", to: "users#show", as: "user_profile"
  end

  # Routes for non-authenticated users
  resources :collections, only: [:index, :show] do
    resources :items, only: [:show] do
      resources :comments, only: [:index]
    end
  end

  # Admin dashboard routes
  scope :dashboard do
    get "/", to: "admin/dashboard#index", as: :dashboard
    resources :users, only: [:index, :update, :destroy], module: "admin" do
      member do
        patch :block
        patch :unblock
        patch :add_admin_role
        patch :remove_admin_role
      end
    end
    resources :topics, except: [:show], module: "admin"
    resources :tags, except: [:show], module: "admin"
  end

  # Reveal health status
  get "/up", to: "rails/health#show", as: :rails_health_check

  # Search route
  get "/search", to: "search#search", as: :search

  # Root path
  root "users#index"

  # 404 page
  get "*path", to: "errors#not_found", via: :all
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user
  has_many :custom_fields, dependent: :destroy
  has_many :items, dependent: :destroy

  validates :name, presence: true
  # accepts_nested_attributes_for :custom_fields, allow_destroy: true
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  include ImageUploadable

  before_action :set_collection, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_user!, only: [:edit, :update, :destroy]
  before_action :load_users, only: [:new, :create, :edit, :update]

  def index
    @collections = Collection.includes(:user).all
  end

  def show
    load_custom_fields
    @items = @collection.items
    @q = @items.ransack(params[:q])

    if params[:q] && params[:q][:s]
      custom_sort_params = params[:q][:s]
      if custom_sort_params.include?("item_custom_field_values_")
        custom_field_id, order = custom_sort_params.match(/item_custom_field_values_(\d+)_value (\w+)/).captures
        @items = @items.joins(:item_custom_field_values)
                       .where(item_custom_field_values: { custom_field_id: custom_field_id })
                       .order("item_custom_field_values.value #{order}")
      else
        @items = @q.result(distinct: true)
      end
    else
      @items = @q.result(distinct: true)
    end

    begin
      @pagy, @items = pagy(@items, items: 10)
    rescue Pagy::OverflowError
      total_pages = (@items.count.to_f / 10).ceil
      @pagy, @items = pagy(@items, items: 10, page: total_pages)
    end

    @items_with_joined_data = @items.map do |item|
      custom_fields = CustomField.where(collection_id: item.collection_id)
      item_custom_field_values = ItemCustomFieldValue.where(item_id: item.id)

      joined_data = custom_fields.joins(:item_custom_field_values)
                                 .where(item_custom_field_values: { item_id: item.id })
                                 .select("custom_fields.label AS custom_field_label, item_custom_field_values.value AS custom_field_value")

      { item: item, joined_data: joined_data }
    end
  end

  def new
    @collection = Collection.new
    @collection.custom_fields.build # Build an initial custom field for the form
  end

  def create
    if current_user.admin? && collection_params[:user_id].present?
      @collection = Collection.new(collection_params.except(:custom_fields))
    else
      @collection = current_user.collections.build(collection_params.except(:user_id, :custom_fields))
    end

    handle_image_upload

    if @collection.save
      # Extract custom field data and create CustomField records
      create_custom_fields(@collection, collection_params[:custom_fields]) if collection_params[:custom_fields].present?

      redirect_to @collection, notice: "Collection was successfully created."
    else
      render :new
    end
  end

  def update
    handle_image_upload

    Rails.logger.debug "Received parameters: #{collection_params.inspect}"

    if @collection.update(collection_params.except(:custom_fields, :image))
      # Update existing custom fields
      update_custom_fields(@collection, collection_params[:custom_fields]) if collection_params[:custom_fields].present?

      Rails.logger.debug "Collection attributes after update: #{@collection.attributes}"

      redirect_to @collection, notice: "Collection was successfully updated."
    else
      render :edit
    end
  end

  def edit
    @collection.custom_fields.build if @collection.custom_fields.empty? # Build an initial custom field if none exist
  end

  def destroy
    delete_image_from_cloudinary(@collection.image) if @collection.image.present?

    if @collection.destroy
      redirect_to user_profile_path, notice: "Collection was successfully destroyed."
    else
      redirect_to user_profile_path, alert: "Failed to destroy collection."
    end
  end

  def delete_custom_field
    custom_field = CustomField.find(params[:custom_field_id])
    collection = custom_field.collection

    if custom_field.destroy
      respond_to do |format|
        format.html { redirect_to edit_collection_path(collection), notice: "Custom field was successfully deleted." }
        format.js { render layout: false } # Handle JavaScript response for remote deletion
      end
    else
      respond_to do |format|
        format.html { redirect_to edit_collection_path(collection), alert: "Failed to delete custom field." }
        format.js { render layout: false, status: :unprocessable_entity } # Handle JavaScript response for failure
      end
    end
  end

  def export_csv
    @collection = Collection.find(params[:id])
    respond_to do |format|
      format.csv do
        send_data @collection.items.to_csv, filename: "collection_items.csv"
      end
    end
  end

  private

  def set_collection
    @collection = Collection.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to collections_path, alert: "Collection not found."
  end

  def collection_params
    params.require(:collection).permit(:name, :topic, :image, :description, :user_id, custom_fields: [:label, :type, :id], q: [:s])
  end

  def authorize_user!
    unless current_user == @collection.user || current_user.admin?
      redirect_to collections_path, alert: "You are not authorized to perform this action."
    end
  end

  def load_users
    @users = User.all if current_user.admin?
  end

  def load_custom_fields
    @custom_fields ||= @collection.custom_fields
  end

  def create_custom_fields(collection, custom_fields)
    custom_fields.each do |field_params|
      collection.custom_fields.create(label: field_params[:label], data_type: field_params[:type])
    end
  end

  def update_custom_fields(collection, custom_fields_params)
    custom_fields_params.each do |field_params|
      if field_params[:id].present?
        # Update existing custom field if ID is present
        custom_field = collection.custom_fields.find_by(id: field_params[:id])
        next unless custom_field # Skip if custom field doesn't exist

        custom_field.update(label: field_params[:label], data_type: field_params[:type])
      else
        # Create new custom field if ID is not present
        collection.custom_fields.create(label: field_params[:label], data_type: field_params[:type])
      end
    end
  end

  def handle_image_upload
    if params[:collection][:image].present?
      encoded_image = Base64.strict_encode64(params[:collection][:image].read)
      cloudinary_response = upload_image_to_cloudinary(encoded_image)

      if cloudinary_response && cloudinary_response["secure_url"]
        delete_image_from_cloudinary(@collection.image) if action_name == "update" && @collection.image.present?
        @collection.image = cloudinary_response["secure_url"]
        flash.now[:notice] = "Image uploaded successfully."
      else
        flash.now[:alert] = "Failed to upload image to Cloudinary"
        render action_name == "create" ? :new : :edit
        return
      end
    end
  end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_collection_dropdown.html.erb
<% if current_user && (collection.user == current_user || current_user.admin?) %>
  <div class="relative">
    <button id="dropdownButton-<%= collection.id %>" data-dropdown-toggle="dropdown-<%= collection.id %>" class="inline-block text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:ring-4 focus:outline-none focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-1.5" type="button">
      <span class="sr-only">Open dropdown</span>
      <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 3">
        <path d="M2 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Zm6.041 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM14 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Z"/>
      </svg>
    </button>
    <!-- Dropdown menu -->
    <div id="dropdown-<%= collection.id %>" class="z-10 hidden text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 absolute right-0 mt-2">
      <ul class="py-2" aria-labelledby="dropdownButton-<%= collection.id %>">
        <li>
          <%= link_to edit_collection_path(collection), class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white" do %>
            Edit
          <% end %>
        </li>
        <li>
          <%= form_with(model: collection, url: collection_path(collection), method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: "inline-block") do %>
            <%= submit_tag 'Delete', class: "block px-4 py-2 text-sm text-red-600 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white" %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
<% end %>

app/views/collections/_collection_items_table.html.erb
<div class="mt-6">
  <div>
    <h3 class="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-2">Items in Collection</h3>
    <table class="w-full text-sm rtl:text-right text-gray-500 dark:text-gray-400">
      <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
        <tr class="text-left" style="text-align: left;">
          <th scope="col" class="px-4 py-4">#</th>
          <th scope="col" class="px-4 py-4">IMAGE</th>
          <th scope="col" class="px-4 py-4"><%= sort_link @q, :name, 'NAME' %></th>
          <th scope="col" class="px-4 py-4"><%= sort_link @q, :created_at, 'CREATED AT' %></th>
          <th scope="col" class="px-4 py-4">
            <%= sort_link(@q, :likes_count, class: "text-red-500 flex gap-1") do %>
              <p class="text-gray-500 dark:text-gray-400">LIKES</p>
              <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 512 512" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg">
                <path fill="currentColor" d="M462.3 62.6C407.5 15.9 326 24.3 275.7 76.2L256 96.5l-19.7-20.3C186.1 24.3 104.5 15.9 49.7 62.6c-62.8 53.6-66.1 149.8-9.9 207.9l193.5 199.8c12.5 12.9 32.8 12.9 45.3 0l193.5-199.8c56.3-58.1 53-154.3-9.8-207.9z"></path>
              </svg>
            <% end %>
          </th>
          <% @custom_fields.each do |custom_field| %>
            <th scope="col" class="px-4 py-4"><%= sort_link @q, "item_custom_field_values_#{custom_field.id}_value", custom_field.label %></th>
          <% end %>
          <% if current_user && (current_user == @collection.user || current_user.admin?) %>
            <th scope="col" class="px-4 py-4">ACTIONS</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @items_with_joined_data.each_with_index do |data, index| %>
          <% item = data[:item] %>
          <% joined_data = data[:joined_data] %>
          <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
            <td class="px-4 py-4"><%= index + 1 %></td>
            <th scope="row" class="flex items-center px-6 py-4 text-gray-900 whitespace-nowrap dark:text-white">
              <%= link_to collection_item_path(item.collection, item), class: "flex items-center" do %>
                <div class="w-24 h-28">
                  <img class="object-cover w-full h-full" src="<%= item.image? ? item.image : asset_path('default_item_img.jpg') %>" alt="<%= item.name %> image">
                </div>
              <% end %>
            </th>
            <td class="px-4 py-4"><%= item.name %></td>
            <td class="px-4 py-4"><%= item.created_at.strftime("%B %d, %Y") %></td>
            <td class="px-4 py-4"><%= item.likes_count %></td>
            <% @custom_fields.each do |custom_field| %>
              <% custom_field_data = joined_data.find { |data| data.custom_field_label == custom_field.label } %>
              <% if custom_field_data %>
                <td class="px-4 py-4"><%= custom_field_data.custom_field_value %></td>
              <% else %>
                <td class="px-4 py-4">-</td>
              <% end %>
            <% end %>
            <% if current_user && (current_user == @collection.user || current_user.admin?) %>
              <td class="px-4 py-4">
                <div class="flex items-center">
                  <div class="">
                    <button id="dropdownActionButton-item<%= item.id %>" data-dropdown-toggle="dropdownAction-item<%= item.id %>" class="inline-flex items-center text-gray-500 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 font-medium rounded-lg text-sm px-3 py-1.5 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700" type="button">
                      <span class="sr-only">Action button</span>
                      Action
                      <svg class="w-2.5 h-2.5 ms-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
                      </svg>
                    </button>
                    <!-- Dropdown menu -->
                    <div id="dropdownAction-item<%= item.id %>" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 dark:divide-gray-600">
                      <ul class="py-1 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownActionButton-item<%= item.id %>">
                        <li>
                          <%= link_to "Edit Item", edit_collection_item_path(item.collection, item), class: "block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-white" %>
                        </li>
                        <li>
                          <%= form_with(url: collection_item_path(item.collection, item), method: :delete, local: true, data: { confirm: "Are you sure you want to delete this item?" }) do |form| %>
                            <%= form.submit "Delete Item", class: "block px-4 py-2 text-sm text-red-600 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-red-600 dark:hover:text-white" %>
                          <% end %>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <% if @pagy && @pagy.pages > 1 %>
    <div class="pagination flex justify-center mt-6">
      <%= render partial: 'shared/pagination', locals: { pagy: @pagy } %>
    </div>
  <% end %>
</div>

app/views/collections/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Collections#create</h1>
  <p>Find me in app/views/collections/create.html.erb</p>
</div>

app/views/collections/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">Collections#destroy</h1>
  <p>Find me in app/views/collections/destroy.html.erb</p>
</div>

app/views/collections/edit.html.erb
<div class="bg-gray-100 dark:bg-gray-900 text-gray-900 dark:text-white">
  <div class="container mx-auto p-6">
    <div class="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-lg">
      <div class="flex justify-between items-center mb-6">
        <h1 class="text-2xl font-bold">Create a new collection</h1>
        <%= link_to 'Return to the profile page', user_profile_path(current_user), class: 'text-gray-600 dark:text-gray-400 hover:text-gray-800 dark:hover:text-gray-200' %>
      </div>
      <%= form_with model: @collection, local: true, html: { class: 'space-y-4' } do |f| %>
        <div class="mb-4">
          <%= f.label :name, class: 'block text-sm font-medium text-gray-700 dark:text-gray-300' %>
          <%= f.text_field :name, class: 'mt-1 block w-full rounded-md bg-gray-100 dark:bg-gray-700 border-gray-300 dark:border-gray-600 text-gray-900 dark:text-white shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50', placeholder: 'Enter collection title' %>
        </div>
        <div class="mb-4">
          <%= f.label :topic, 'Select Collection Topic', class: 'block text-sm font-medium text-gray-700 dark:text-gray-300' %>
          <%= f.select :topic, options_for_select([['Select collection topic', nil]] + Topic.all.map { |topic| [topic.name, topic.name] }, @collection.topic), {}, class: 'mt-1 block w-full rounded-md bg-gray-100 dark:bg-gray-700 border-gray-300 dark:border-gray-600 text-gray-900 dark:text-white shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50' %>
        </div>
        <div class="mb-4">
          <%= f.label :image, class: 'block text-sm font-medium text-gray-700 dark:text-gray-300' %>
          <div class="flex items-center justify-center w-full">
            <label for="file-upload" class="flex flex-col items-center justify-center w-full h-32 border-2 border-dashed rounded-lg cursor-pointer bg-gray-50 dark:bg-gray-700 border-gray-300 dark:border-gray-600 hover:bg-gray-100 dark:hover:bg-gray-600">
              <div class="flex flex-col items-center justify-center pt-5 pb-6">
                <svg aria-hidden="true" class="w-10 h-10 mb-3 text-gray-400 dark:text-gray-300" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16V12M7 8H7.01M7 16V16C7 16 5 18 5 20H19C19 18 17 16 17 16V16M7 16H17M7 16V16C7 16 9 14 11 14H13C15 14 17 16 17 16V16"></path></svg>
                <p id="file-name" class="mb-2 text-sm text-gray-400 dark:text-gray-300"><span class="font-semibold">Upload</span> or drop a file right here</p>
                <p class="text-xs text-gray-400 dark:text-gray-300">JPEG, JPG, PNG, GIF</p>
              </div>
              <%= f.file_field :image, class: 'hidden', id: 'file-upload', onchange: 'showFileName(this)' %>
            </label>
          </div>
          <p class="mt-1 text-sm text-gray-500 dark:text-gray-400">If you don't select an image, the default one will be set automatically</p>
        </div>
        <div class="mb-4">
          <%= f.label :description, class: 'block text-sm font-medium text-gray-700 dark:text-gray-300' %>
          <%= f.text_area :description, rows: 4, class: 'mt-1 block w-full rounded-md bg-gray-100 dark:bg-gray-700 border-gray-300 dark:border-gray-600 text-gray-900 dark:text-white shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50', placeholder: 'Write a description...' %>
        </div>
        <div class="mb-4" data-controller="custom-fields">
          <h2 class="text-xl font-bold mb-2">Custom fields</h2>
          <button type="button" data-action="custom-fields#addField" class="mb-4 px-4 py-2 text-sm font-medium text-white bg-blue-600 rounded-lg shadow-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2">+ Add field</button>
          <div data-custom-fields-target="fieldsContainer">
            <% @collection.custom_fields.each do |custom_field| %>
              <div class="flex items-center mb-2 custom-field">
                <!-- Hidden input field to store custom field ID -->
                <input type="hidden" name="collection[custom_fields][][id]" value="<%= custom_field.id %>">
                <input type="text" name="collection[custom_fields][][label]" value="<%= custom_field.label %>" class="flex-1 p-2 mr-2 rounded-md bg-gray-100 dark:bg-gray-700 border-gray-300 dark:border-gray-600 text-gray-900 dark:text-white shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50" placeholder="Custom field's label">
                <select name="collection[custom_fields][][type]" class="p-2 rounded-md bg-gray-100 dark:bg-gray-700 border-gray-300 dark:border-gray-600 text-gray-900 dark:text-white shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50">
                  <option value="string" <%= 'selected="selected"' if custom_field.data_type == "string" %>>String</option>
      <option value="number" <%= 'selected="selected"' if custom_field.data_type == "number" %>>Number</option>
      <option value="date" <%= 'selected="selected"' if custom_field.data_type == "date" %>>Date</option>
      <option value="boolean" <%= 'selected="selected"' if custom_field.data_type == "boolean" %>>Boolean</option>
      <option value="checkbox" <%= 'selected="selected"' if custom_field.data_type == "checkbox" %>>Checkbox</option>
      <option value="textarea" <%= 'selected="selected"' if custom_field.data_type == "textarea" %>>Textarea</option>
    </select>
    <% if custom_field.id.present? %>
    <%= link_to '-', delete_custom_field_collection_path(@collection, custom_field_id: custom_field.id), method: :delete, data: { confirm: "Are you sure you want to delete this custom field?", turbo_method: :delete }, class: "ml-2 px-4 py-2 text-sm font-medium text-white bg-red-600 rounded-lg shadow-md hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2" %>
  <% end %>
  </div>
                  <% end %>
                </div>
                <template data-custom-fields-target="template">
                  <div class="flex items-center mb-2 custom-field">
                    <input type="text" name="collection[custom_fields][][label]" class="flex-1 p-2 mr-2 rounded-md bg-gray-100 dark:bg-gray-700 border-gray-300 dark:border-gray-600 text-gray-900 dark:text-white shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50" placeholder="Custom field's label">
                    <select name="collection[custom_fields][][type]" class="p-2 rounded-md bg-gray-100 dark:bg-gray-700 border-gray-300 dark:border-gray-600 text-gray-900 dark:text-white shadow-sm focus:border-blue-500 focus:ring focus:ring-blue-500 focus:ring-opacity-50">
                      <option value="string">String</option>
                      <option value="number">Number</option>
                      <option value="date">Date</option>
                      <option value="boolean">Boolean</option>
                      <option value="checkbox">Checkbox</option>
                      <option value="textarea">Textarea</option>
                    </select>
                    <button type="button" data-action="custom-fields#removeField" class="ml-2 px-4 py-2 text-sm font-medium text-white bg-red-600 rounded-lg shadow-md hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-offset-2">-</button>
                  </div>
                </template>
              </div>
              <div class="flex justify-end">
                <%= link_to 'Cancel', collections_path, class: 'mr-2 px-4 py-2 text-sm font-medium text-white bg-gray-600 dark:bg-gray-700 rounded-lg shadow-md hover:bg-gray-700 dark:hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2' %>
                <%= f.submit 'Update', class: 'px-4 py-2 text-sm font-medium text-white bg-blue-600 rounded-lg shadow-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <script>
        function showFileName(input) {
          const fileName = input.files[0].name;
          document.getElementById('file-name').innerHTML = fileName;
        }
      </script>

app/views/collections/show.html.erb
<div class="bg-white p-6 w-full rounded-lg shadow-md hover:shadow-lg transition-shadow duration-300 dark:bg-gray-800">
  <div class="flex flex-col md:flex-row mb-4">
    <div class="md:w-1/3 w-full mb-4 md:mb-0 md:mr-4">
      <div class="relative w-full aspect-w-1 aspect-h-1">
        <img src="<%= @collection.image.present? ? @collection.image : asset_path('default_collection_img.jpg') %>" alt="<%= @collection.name %>" class="absolute top-0 left-0 w-full h-full object-cover rounded-md">
      </div>
    </div>
    <div class="md:w-2/3 w-full">
      <h3 class="text-2xl font-semibold text-gray-900 dark:text-gray-100 mb-2">
        <%= @collection.name %>
      </h3>
      <p class="text-sm text-gray-600 dark:text-gray-400 mb-4"><%= @collection.topic %></p>
      <p class="text-gray-900 dark:text-gray-100 mb-2"><%= @collection.description %></p>
      <p class="text-sm text-gray-500 dark:text-gray-300 mb-2">Items quantity: <%= @collection.items_count %></p>
      <p class="text-xs text-gray-500 dark:text-gray-300">Created by <%= link_to @collection.user.username, user_profile_path(@collection.user), class: "text-blue-500 hover:underline" %></p>
      <p class="text-xs text-gray-500 dark:text-gray-300 mb-4"><%= @collection.created_at.strftime("%d.%m.%Y at %H:%M:%S") %></p>
      <div class="flex space-x-2 mb-2">
        <% if current_user && (current_user == @collection.user || current_user.admin?) %>
          <%= link_to 'Add New Item', new_collection_item_path(@collection), class: 'bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded' %>
        <% end %>
        <% if user_signed_in? && @collection.items.any? %>
          <%= link_to 'Export to CSV', export_csv_collection_path(@collection, format: :csv), class: 'bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded' %>
        <% end %>
        <% if user_signed_in? %>
          <%= link_to 'Create Support Ticket', new_ticket_path(collection_id: @collection.id), class: 'bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded' %>
        <% end %>
      </div>
      <%= render partial: 'collection_dropdown', locals: { collection: @collection } %>
    </div>
  </div>
  <div class="border-t border-gray-100 dark:border-gray-700">
    <%= render partial: 'collection_items_table'%>
  </div>
</div>

app/views/collections/update.html.erb
<div>
  <h1 class="font-bold text-4xl">Collections#update</h1>
  <p>Find me in app/views/collections/update.html.erb</p>
</div>