config/routes.rb
Rails.application.routes.draw do
  get "search/search"
  devise_for :users, controllers: {
                       registrations: "users/registrations",
                       omniauth_callbacks: "users/omniauth_callbacks",
                     }

  # Translation endpoint
  get "/translate", to: "translations#translate"

  # Routes for authenticated users
  authenticate :user do
    resources :collections, except: [:index, :show] do
      resources :items, except: [:show] do
        resources :comments, only: [:create, :destroy]
        resources :likes, only: [:create, :destroy]
      end

      # Add route for CSV export
      member do
        get "export_csv"
        delete "delete_custom_field/:custom_field_id", to: "collections#delete_custom_field", as: "delete_custom_field"
      end
    end

    # Move these actions inside the existing resources block
    # resources :collections, only: [:new, :create, :edit, :update, :destroy]

    resources :tickets, only: [:new, :create]

    # Profile route
    get "profile/:id", to: "users#show", as: "user_profile"
  end

  # Routes for non-authenticated users
  resources :collections, only: [:index, :show] do
    resources :items, only: [:show] do
      resources :comments, only: [:index]
    end
  end

  # Admin dashboard routes
  scope :dashboard do
    get "/", to: "admin/dashboard#index", as: :dashboard
    resources :users, only: [:index, :update, :destroy], module: "admin" do
      member do
        patch :block
        patch :unblock
        patch :add_admin_role
        patch :remove_admin_role
      end
    end
    resources :topics, except: [:show], module: "admin"
    resources :tags, except: [:show], module: "admin"
  end

  # Reveal health status
  get "/up", to: "rails/health#show", as: :rails_health_check

  # Search route
  get "/search", to: "search#search", as: :search

  # Root path
  root "users#index"

  # 404 page
  get "*path", to: "errors#not_found", via: :all
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_admin!
  before_action :load_data, only: [:index]

  def index
    begin
      @pagy, @users = pagy(@users, items: 2)
    rescue Pagy::OverflowError
      total_pages = (@users.count.to_f / 10).ceil
      @pagy, @users = pagy(@users, items: 10, page: total_pages)
    end
  end

  private

  def ensure_admin!
    redirect_to root_path, alert: "You are not authorized to access this page." unless current_user.admin?
  end

  def load_data
    @q_users = User.ransack(params[:q])
    @q_topics = Topic.includes(:user).ransack(params[:q])
    @q_tags = Tag.includes(:user).ransack(params[:q])
    @users = @q_users.result(distinct: true)
    @topics = @q_topics.result(distinct: true).order(created_at: :desc)
    @tags = @q_tags.result(distinct: true).order(created_at: :desc)
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/views/admin/dashboard/_tag_table.html.erb
<div class="relative overflow-x-auto sm:rounded-lg p-4">
  <div class="flex items-center justify-between flex-column flex-wrap md:flex-row space-y-4 md:space-y-0 p-4 bg-white dark:bg-gray-900">
    <div>
      <a href="<%= new_tag_path %>" class="block px-4 py-2 text-sm font-medium text-gray-900 bg-blue-500 rounded-lg shadow-md hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 focus:ring-offset-gray-50 dark:bg-blue-600 dark:text-white dark:hover:bg-blue-700">New Tag</a>
    </div>
    <label for="table-search" class="sr-only">Search</label>
    <div class="relative">
      <div class="absolute inset-y-0 rtl:inset-r-0 start-0 flex items-center ps-3 pointer-events-none">
        <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
        </svg>
      </div>
      <input type="text" id="table-search-tags" class="block p-2 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg w-80 bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Search for tags">
    </div>
  </div>
  <table class="w-full text-sm rtl:text-right text-gray-500 dark:text-gray-400">
    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
      <tr class="text-left" style="text-align: left;">
        <th scope="col" class="px-4 py-4">ID</th>
        <th scope="col" class="px-4 py-4"><%= sort_link @q_tags, :name, 'TAG' %></th>
        <th scope="col" class="px-4 py-4">USER NAME</th>
        <th scope="col" class="px-4 py-4"><%= sort_link @q_tags, :created_at, 'CREATED AT' %></th>
        <th scope="col" class="px-4 py-4">ACTION</th>
      </tr>
    </thead>
    <tbody>
      <% tags.each do |tag| %>
        <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
          <td class="px-4 py-4"><%= tag.id %></td>
          <td class="px-4 py-4"><%= tag.name %></td>
          <td class="px-4 py-4"><%= tag.user.username %></td>
          <td class="px-4 py-2 whitespace-nowrap"><%= tag.created_at.strftime("%B %d, %Y") %></td>
          <td class="px-4 py-4">
            <div class="flex items-center">
              <div class="">
                <button id="dropdownActionButton-tag<%= tag.id %>" data-dropdown-toggle="dropdownAction-tag<%= tag.id %>" class="inline-flex items-center text-gray-500 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 font-medium rounded-lg text-sm px-3 py-1.5 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700" type="button">
                  <span class="sr-only">Action button</span>
                  Action
                  <svg class="w-2.5 h-2.5 ms-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
                  </svg>
                </button>
                <!-- Dropdown menu -->
                <div id="dropdownAction-tag<%= tag.id %>" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 dark:divide-gray-600">
                  <ul class="py-1 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownActionButton-tag<%= tag.id %>">
                    <li>
                      <%= link_to "Edit Tag", edit_tag_path(tag), method: :patch, data: { confirm: "Are you sure you want to edit this tag?" }, class: "block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-white" %>
                    </li>
                    <li>
                      <%= form_with(url: tag_path(tag), method: :delete, local: true, data: { confirm: "Are you sure you want to delete this tag?" }) do |form| %>
                        <%= form.submit "Delete Tag", class: "block px-4 py-2 text-sm text-red-600 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-red-600 dark:hover:text-white" %>
                      <% end %>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/dashboard/_topic_table.html.erb
<div class="relative overflow-x-auto sm:rounded-lg p-4">
  <div class="flex items-center justify-between flex-column flex-wrap md:flex-row space-y-4 md:space-y-0 p-4 bg-white dark:bg-gray-900">
    <div>
      <a href="<%= new_topic_path %>" class="block px-4 py-2 text-sm font-medium text-gray-900 bg-blue-500 rounded-lg shadow-md hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 focus:ring-offset-gray-50 dark:bg-blue-600 dark:text-white dark:hover:bg-blue-700">New Topic</a>
    </div>
    <label for="table-search" class="sr-only">Search</label>
    <div class="relative">
      <div class="absolute inset-y-0 rtl:inset-r-0 start-0 flex items-center ps-3 pointer-events-none">
        <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
        </svg>
      </div>
      <input type="text" id="table-search-topics" class="block p-2 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg w-80 bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Search for topics">
    </div>
  </div>
  <table class="w-full text-sm rtl:text-right text-gray-500 dark:text-gray-400">
    <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
      <tr class="text-left" style="text-align: left;">
        <th scope="col" class="px-4 py-4">ID</th>
        <th scope="col" class="px-4 py-4"><%= sort_link @q_topics, :name, 'TOPIC' %></th>
        <th scope="col" class="px-4 py-4">USER NAME</th>
        <th scope="col" class="px-4 py-4"><%= sort_link @q_topics, :created_at, 'CREATED AT' %></th>
        <th scope="col" class="px-4 py-4">ACTION</th>
      </tr>
    </thead>
    <tbody>
      <% topics.each do |topic| %>
        <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
          <td class="px-4 py-4"><%= topic.id %></td>
          <td class="px-4 py-4"><%= topic.name %></td>
          <td class="px-4 py-4"><%= topic.user.username %></td>
          <td class="px-4 py-2 whitespace-nowrap"><%= topic.created_at.strftime("%B %d, %Y") %></td>
          <td class="px-4 py-4">
            <div class="flex items-center">
              <div class="">
                <button id="dropdownActionButton-topic<%= topic.id %>" data-dropdown-toggle="dropdownAction-topic<%= topic.id %>" class="inline-flex items-center text-gray-500 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 font-medium rounded-lg text-sm px-3 py-1.5 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700" type="button">
                  <span class="sr-only">Action button</span>
                  Action
                  <svg class="w-2.5 h-2.5 ms-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                    <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
                  </svg>
                </button>
                <!-- Dropdown menu -->
                <div id="dropdownAction-topic<%= topic.id %>" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 dark:divide-gray-600">
                  <ul class="py-1 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownActionButton-topic<%= topic.id %>">
                    <li>
                      <%= link_to "Edit Topic", edit_topic_path(topic), method: :patch, data: { confirm: "Are you sure you want to edit this topic?" }, class: "block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-white" %>
                    </li>
                    <li>
                      <%= form_with(url: topic_path(topic), method: :delete, local: true, data: { confirm: "Are you sure you want to delete this topic?" }) do |form| %>
                        <%= form.submit "Delete Topic", class: "block px-4 py-2 text-sm text-red-600 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-red-600 dark:hover:text-white" %>
                      <% end %>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/admin/dashboard/_user_table.html.erb
<div class="relative overflow-x-auto sm:rounded-lg p-4">
  <div>
    <div class="flex items-center justify-between flex-column flex-wrap md:flex-row space-y-4 md:space-y-0 p-4 bg-white dark:bg-gray-900">
      <label for="table-search" class="sr-only">Search</label>
      <div class="relative">
        <div class="absolute inset-y-0 rtl:inset-r-0 start-0 flex items-center ps-3 pointer-events-none">
          <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 20">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z"/>
          </svg>
        </div>
        <input type="text" id="table-search-users" class="block p-2 ps-10 text-sm text-gray-900 border border-gray-300 rounded-lg w-80 bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Search for users">
      </div>
    </div>
    <table class="w-full text-sm rtl:text-right text-gray-500 dark:text-gray-400">
      <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
        <tr class="text-left" style="text-align: left;">
          <th scope="col" class="px-4 py-4">ID</th>
          <th scope="col" class="px-4 py-4"><%= sort_link @q_users, :username, 'NAME' %></th>
          <th scope="col" class="px-4 py-4"><%= sort_link @q_users, :role, 'POSITION' %></th>
          <th scope="col" class="px-4 py-4"><%= sort_link @q_users, :status, 'STATUS' %></th>
          <th scope="col" class="px-4 py-4">ACTION</th>
        </tr>
      </thead>
      <tbody>
        <% users.each do |user| %>
          <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
            <td class="px-4 py-4"><%= user.id %></td>
            <th scope="row" class="flex items-center px-6 py-4 text-gray-900 whitespace-nowrap dark:text-white">
              <%= link_to user_profile_path(user), class: "flex items-center" do %>
                <img class="w-10 h-10 rounded-full object-cover" src="<%= user.profile_image.present? ? user.profile_image : asset_path('default_avatar.png') %>" alt="<%= user.username %> image" style="width: 40px; height: 40px;">
                <div class="ps-3 ml-2 text-left">
                  <div class="text-base flex items-center font-semibold"><%= user.username %></div>
                  <div class="font-normal text-gray-500"><%= user.email %></div>
                </div>
              <% end %>
            </th>
            <td class="px-4 py-4"><%= user.role %></td>
            <td class="px-4 py-4">
              <div class="flex items-center">
                <div class="h-2.5 w-2.5 rounded-full <%= user.active? ? 'bg-green-500' : 'bg-red-500' %> me-2"></div>
                <%= user.active? ? 'Active' : 'Blocked' %>
              </div>
            </td>
            <td class="px-4 py-4">
              <div class="flex items-center">
                <div class="">
                  <button id="dropdownActionButton<%= user.id %>" data-dropdown-toggle="dropdownAction<%= user.id %>" class="inline-flex items-center text-gray-500 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 font-medium rounded-lg text-sm px-3 py-1.5 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700" type="button">
                    <span class="sr-only">Action button</span>
                    Action
                    <svg class="w-2.5 h-2.5 ms-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
                      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
                    </svg>
                  </button>
                  <!-- Dropdown menu -->
                  <div id="dropdownAction<%= user.id %>" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 dark:divide-gray-600">
                    <ul class="py-1 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownActionButton<%= user.id %>">
                      <% if user.active? %>
                        <li>
                          <%= form_with(url: block_user_path(user), method: :patch, local: true, data: { confirm: "Are you sure you want to block this user?" }) do |form| %>
                            <%= form.submit "Block account", class: "block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-white" %>
                          <% end %>
                        </li>
                      <% elsif user.blocked? %>
                        <li>
                          <%= form_with(url: unblock_user_path(user), method: :patch, local: true, data: { confirm: "Are you sure you want to activate this user?" }) do |form| %>
                            <%= form.submit "Activate account", class: "block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-white" %>
                          <% end %>
                        </li>
                      <% end %>
                      <% if user.regular? %>
                        <li>
                          <%= form_with(url: add_admin_role_user_path(user), method: :patch, local: true, data: { confirm: "Are you sure you want to promote this user to admin?" }) do |form| %>
                            <%= form.submit "Promote to admin", class: "block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-white" %>
                          <% end %>
                        </li>
                      <% elsif user.admin? %>
                        <li>
                          <%= form_with(url: remove_admin_role_user_path(user), method: :patch, local: true, data: { confirm: "Are you sure you want to demote this user to regular?" }) do |form| %>
                            <%= form.submit "Demote to regular", class: "block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-white" %>
                          <% end %>
                        </li>
                      <% end %>
                    </ul>
                    <div class="py-1">
                      <%= form_with(url: user_path(user), method: :delete, local: true, data: { confirm: "Are you sure you want to delete this user?" }) do |form| %>
                        <%= form.submit "Delete User", class: "block px-4 py-2 text-sm text-red-600 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-red-600 dark:hover:text-white" %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <% if @pagy && @pagy.pages > 1 %>
    <div class="pagination flex justify-center mt-6">
      <%= render partial: 'shared/pagination', locals: { pagy: @pagy } %>
    </div>
  <% end %>
</div>

app/views/admin/dashboard/index.html.erb
<div class="p-4 bg-white dark:bg-gray-800 rounded-lg shadow-md">
  <div class="mb-4 border-b border-gray-200 dark:border-gray-700">
    <ul class="flex flex-wrap -mb-px text-sm font-medium text-center" id="default-tab" data-tabs-toggle="#default-tab-content" role="tablist">
      <li class="me-2" role="presentation">
        <button class="inline-block p-4 border-b-2 rounded-t-lg focus:outline-none" id="users-tab" data-tabs-target="#users" type="button" role="tab" aria-controls="users" aria-selected="false">All Users</button>
      </li>
      <li class="me-2" role="presentation">
        <button class="inline-block p-4 border-b-2 rounded-t-lg focus:outline-none hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" id="topics-tab" data-tabs-target="#topics" type="button" role="tab" aria-controls="topics" aria-selected="false">All Topics</button>
      </li>
      <li class="me-2" role="presentation">
        <button class="inline-block p-4 border-b-2 rounded-t-lg focus:outline-none hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" id="tags-tab" data-tabs-target="#tags" type="button" role="tab" aria-controls="tags" aria-selected="false">All Tags</button>
      </li>
    </ul>
  </div>
  <div id="default-tab-content">
    <div class="hidden" id="users" role="tabpanel" aria-labelledby="users-tab">
      <%= render partial: 'user_table', locals: { users: @users} %>
    </div>
    <div class="hidden" id="topics" role="tabpanel" aria-labelledby="topics-tab">
      <%= render partial: 'topic_table', locals: { topics: @topics} %>
    </div>
    <div class="hidden" id="tags" role="tabpanel" aria-labelledby="tags-tab">
      <%= render partial: 'tag_table', locals: { tags: @tags} %>
    </div>
  </div>
</div>