config/routes.rb
Rails.application.routes.draw do
  get "search/search"
  devise_for :users, controllers: {
                       registrations: "users/registrations",
                       omniauth_callbacks: "users/omniauth_callbacks",
                     }

  # Translation endpoint
  get "/translate", to: "translations#translate"

  # Routes for authenticated users
  authenticate :user do
    resources :collections, except: [:index, :show] do
      resources :items, except: [:show] do
        resources :comments, only: [:create, :destroy]
        resources :likes, only: [:create, :destroy]
      end

      # Add route for CSV export
      member do
        get "export_csv"
        delete "delete_custom_field/:custom_field_id", to: "collections#delete_custom_field", as: "delete_custom_field"
      end
    end

    # Move these actions inside the existing resources block
    # resources :collections, only: [:new, :create, :edit, :update, :destroy]

    resources :tickets, only: [:new, :create]

    # Profile route
    get "profile/:id", to: "users#show", as: "user_profile"
  end

  # Routes for non-authenticated users
  resources :collections, only: [:index, :show] do
    resources :items, only: [:show] do
      resources :comments, only: [:index]
    end
  end

  # Admin dashboard routes
  scope :dashboard do
    get "/", to: "admin/dashboard#index", as: :dashboard
    resources :users, only: [:index, :update, :destroy], module: "admin" do
      member do
        patch :block
        patch :unblock
        patch :add_admin_role
        patch :remove_admin_role
      end
    end
    resources :topics, except: [:show], module: "admin"
    resources :tags, except: [:show], module: "admin"
  end

  # Reveal health status
  get "/up", to: "rails/health#show", as: :rails_health_check

  # Search route
  get "/search", to: "search#search", as: :search

  # Root path
  root "users#index"

  # 404 page
  get "*path", to: "errors#not_found", via: :all
end

app/views/shared/_collection.html.erb
<% @collections.each do |collection| %>
  <div class="bg-gray-100 dark:bg-gray-700 p-4 rounded-lg shadow-md relative">
    <%= link_to collection_path(collection) do %>
      <img src="<%= collection.image.present? ? collection.image : asset_path('default_collection_img.jpg') %>" alt="<%= collection.name %>" class="w-full h-40 object-cover rounded-md mb-4">
    <% end %>
    <div class="flex justify-between items-center mb-2">
      <h3 class="text-lg font-semibold text-gray-900 dark:text-gray-100"><%= link_to collection.name, collection_path(collection), class: "hover:underline" %></h3>
      <% if current_user && (collection.user == current_user || current_user.admin?) %>
        <div class="relative">
          <button id="dropdownButton-<%= collection.id %>" data-dropdown-toggle="dropdown-<%= collection.id %>" class="inline-block text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:ring-4 focus:outline-none focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-1.5" type="button">
            <span class="sr-only">Open dropdown</span>
            <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 3">
              <path d="M2 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Zm6.041 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM14 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Z"/>
            </svg>
          </button>
          <!-- Dropdown menu -->
          <div id="dropdown-<%= collection.id %>" class="z-10 hidden text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 absolute right-0 mt-2">
            <ul class="py-2" aria-labelledby="dropdownButton-<%= collection.id %>">
              <li>
                <%= link_to edit_collection_path(collection), class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white" do %>
                  Edit
                <% end %>
              </li>
              <li>
                <%= form_with(model: collection, url: collection_path(collection), method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: "inline-block") do %>
                  <%= submit_tag 'Delete', class: "block px-4 py-2 text-sm text-red-600 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white" %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
    <p class="text-sm text-gray-600 dark:text-gray-400"><%= collection.topic %></p>
    <p class="text-sm text-gray-500 dark:text-gray-300">Items quantity: <%= collection.items_count %></p>
    <p class="text-xs text-gray-500 dark:text-gray-300 mt-2">Created by <%= link_to collection.user.username, user_profile_path(collection.user), class: "text-blue-500 hover:underline" %></p>
    <p class="text-xs text-gray-500 dark:text-gray-300"><%= collection.created_at.strftime("%d.%m.%Y at %H:%M:%S") %></p>
  </div>
<% end %>

app/views/shared/_item.html.erb
<% @items.each do |item| %>
  <div class="bg-gray-100 dark:bg-gray-700 p-4 rounded-lg shadow-md relative">
    <%= link_to collection_item_path(item.collection, item) do %>
      <img src="<%= item.image? ? item.image : asset_path('default_item_img.jpg') %>" alt="<%= item.name %>" class="w-full h-40 object-cover rounded-md mb-4">
    <% end %>
    <div class="flex justify-between items-center mb-2">
      <h3 class="text-lg font-semibold text-gray-900 dark:text-gray-100"><%= link_to item.name, collection_item_path(item.collection, item), class: "hover:underline" %></h3>
      <% if current_user && (item.collection.user == current_user || current_user.admin?) %>
        <div class="relative">
          <button id="dropdownButton-<%= item.id %>" data-dropdown-toggle="dropdown-<%= item.id %>" class="inline-block text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:ring-4 focus:outline-none focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-1.5" type="button">
            <span class="sr-only">Open dropdown</span>
            <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 3">
              <path d="M2 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Zm6.041 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM14 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Z"/>
            </svg>
          </button>
          <!-- Dropdown menu -->
          <div id="dropdown-<%= item.id %>" class="z-10 hidden text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 absolute right-0 mt-2">
            <ul class="py-2" aria-labelledby="dropdownButton-<%= item.id %>">
              <li>
                <%= link_to edit_collection_item_path(item.collection, item), class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white" do %>
                  Edit
                <% end %>
              </li>
              <li>
                <%= form_with(model: item, url: edit_collection_item_path(item.collection, item), method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: "inline-block") do %>
                  <%= submit_tag 'Delete', class: "block px-4 py-2 text-sm text-red-600 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white" %>
                <% end %>
              </li>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
    <% if item.tags.any? %>
      <div class="flex flex-wrap mb-4">
        <h4 class="text-lg font-semibold text-gray-900 dark:text-gray-100 mr-2">Tags:</h4>
        <% item.tags.each do |tag| %>
          <span class="bg-gray-200 dark:bg-gray-800 px-2 py-1 rounded text-sm mr-2 mb-2 dark:text-gray-300"><%= tag %></span>
        <% end %>
      </div>
    <% end %>
    <p class="text-sm text-gray-500 dark:text-gray-300 mb-2">
      Collection: <%= link_to item.collection.name, collection_path(item.collection), class: "text-blue-500 hover:underline" %>
    </p>
    <% if user_signed_in? %>
      <p class="text-xs text-gray-500 dark:text-gray-300">
        Added by <%= link_to item.collection.user.username, user_profile_path(item.collection.user), class: "text-blue-500 hover:underline" %>
      </p>
    <% end %>
    <p class="text-xs text-gray-500 dark:text-gray-300 mb-4">
      <%= item.created_at.strftime("%d.%m.%Y at %H:%M:%S") %>
    </p>
  </div>
<% end %>

app/views/shared/_pagination.html.erb
<nav aria-label="Page navigation example">
  <ul class="flex items-center -space-x-px h-8 text-sm">
    <% if pagy.prev %>
      <li>
        <%= link_to raw('<svg class="w-2.5 h-2.5 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 1 1 5l4 4"/></svg>'),
                    url_for(page: pagy.prev), class: 'flex items-center justify-center px-3 h-8 ms-0 leading-tight text-gray-500 bg-white border border-e-0 border-gray-300 rounded-s-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white', 'aria-label' => 'Previous' %>
      </li>
    <% else %>
      <li>
        <span class="flex items-center justify-center px-3 h-8 ms-0 leading-tight text-gray-500 bg-white border border-e-0 border-gray-300 rounded-s-lg opacity-50 cursor-not-allowed dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400">Previous</span>
      </li>
    <% end %>
    <% pagy.series.each do |page| %>
      <li>
        <%= link_to page, url_for(page: page), class: "flex items-center justify-center px-3 h-8 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white #{'text-blue-600 border-blue-300 bg-blue-50 hover:bg-blue-100 hover:text-blue-700 dark:border-gray-700 dark:bg-gray-700 dark:text-white' if pagy.page == page}" %>
      </li>
    <% end %>
    <% if pagy.next %>
      <li>
        <%= link_to raw('<svg class="w-2.5 h-2.5 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/></svg>'),
                    url_for(page: pagy.next), class: 'flex items-center justify-center px-3 h-8 ms-0 leading-tight text-gray-500 bg-white border border-e-0 border-gray-300 rounded-e-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white', 'aria-label' => 'Next' %>
      </li>
    <% else %>
      <li>
        <span class="flex items-center justify-center px-3 h-8 ms-0 leading-tight text-gray-500 bg-white border border-e-0 border-gray-300 rounded-e-lg opacity-50 cursor-not-allowed dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400">Next</span>
      </li>
    <% end %>
  </ul>
</nav>

app/views/shared/_toast.html.erb
<% if notice %>
  <div id="toast-success" data-controller="toast"
    class="toast-message transition transform duration-1000 absolute bottom-5 right-5 flex items-center z-50 w-full max-w-xs p-4 mb-4 text-gray-500 bg-white rounded-lg shadow dark:text-gray-400 dark:bg-gray-800"
    role="alert">
    <div class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 text-green-500 bg-green-100 rounded-lg dark:bg-green-800 dark:text-green-200">
      <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clip-rule="evenodd"></path>
      </svg>
      <span class="sr-only">Check icon</span>
    </div>
    <div class="ml-3 text-sm font-normal"><%= notice %></div>
    <button type="button" class="close-toast ml-auto -mx-1.5 -my-1.5 bg-white text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex h-8 w-8 dark:text-gray-500 dark:hover:text-white dark:bg-gray-800 dark:hover:bg-gray-700" aria-label="Close">
      <span class="sr-only">Close</span>
      <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
      </svg>
    </button>
  </div>
<% end %>
<% if alert %>
  <div id="toast-error" data-controller="toast"
    class="toast-message z-50 transition transform duration-1000 absolute bottom-5 right-5 flex items-center w-full max-w-xs p-4 mb-4 text-gray-500 bg-white rounded-lg shadow dark:text-gray-400 dark:bg-gray-800"
    role="alert">
    <div class="inline-flex items-center justify-center flex-shrink-0 w-8 h-8 text-red-500 bg-red-100 rounded-lg dark:bg-red-800 dark:text-red-200">
      <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
      </svg>
      <span class="sr-only">Error icon</span>
    </div>
    <div class="ml-3 text-sm font-normal"><%= alert %></div>
    <button type="button" class="close-toast ml-auto -mx-1.5 -my-1.5 bg-white text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex h-8 w-8 dark:text-gray-500 dark:hover:text-white dark:bg-gray-800 dark:hover:bg-gray-700" aria-label="Close">
      <span class="sr-only">Close</span>
      <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
        <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
      </svg>
    </button>
  </div>
<% end %>