config/routes.rb
Rails.application.routes.draw do
  get "search/search"
  devise_for :users, controllers: {
                       registrations: "users/registrations",
                       omniauth_callbacks: "users/omniauth_callbacks",
                     }

  # Translation endpoint
  get "/translate", to: "translations#translate"

  # Routes for authenticated users
  authenticate :user do
    resources :collections, except: [:index, :show] do
      resources :items, except: [:show] do
        resources :comments, only: [:create, :destroy]
        resources :likes, only: [:create, :destroy]
      end

      # Add route for CSV export
      member do
        get "export_csv"
        delete "delete_custom_field/:custom_field_id", to: "collections#delete_custom_field", as: "delete_custom_field"
      end
    end

    # Move these actions inside the existing resources block
    # resources :collections, only: [:new, :create, :edit, :update, :destroy]

    resources :tickets, only: [:new, :create]

    # Profile route
    get "profile/:id", to: "users#show", as: "user_profile"
  end

  # Routes for non-authenticated users
  resources :collections, only: [:index, :show] do
    resources :items, only: [:show] do
      resources :comments, only: [:index]
    end
  end

  # Admin dashboard routes
  scope :dashboard do
    get "/", to: "admin/dashboard#index", as: :dashboard
    resources :users, only: [:index, :update, :destroy], module: "admin" do
      member do
        patch :block
        patch :unblock
        patch :add_admin_role
        patch :remove_admin_role
      end
    end
    resources :topics, except: [:show], module: "admin"
    resources :tags, except: [:show], module: "admin"
  end

  # Reveal health status
  get "/up", to: "rails/health#show", as: :rails_health_check

  # Search route
  get "/search", to: "search#search", as: :search

  # Root path
  root "users#index"

  # 404 page
  get "*path", to: "errors#not_found", via: :all
end

app/models/item.rb
class Item < ApplicationRecord
  require "csv"
  belongs_to :collection, counter_cache: true
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :item_custom_field_values, dependent: :destroy  # Corrected association name

  validates :name, presence: true

  accepts_nested_attributes_for :item_custom_field_values

  def self.ransackable_attributes(auth_object = nil)
    ["collection_id", "comments_count", "created_at", "description", "id", "image", "likes_count", "name", "tags", "updated_at"]  # Removed "id_value" attribute
  end

  def self.ransackable_associations(auth_object = nil)
    ["collection", "comments", "likes"]  # Removed "item_custom_field_values" association
  end

  def self.to_csv
    CSV.generate(headers: true) do |csv|
      custom_field_labels = CustomField.pluck(:label)

      csv << ["Name", "Image URL", "Description", "Created At", *custom_field_labels]

      all.each do |item|
        custom_field_values = custom_field_values_for_item(item)
        csv << [
          item.name,
          item.image,
          item.description,
          item.created_at,
          *custom_field_values,
        ]
      end
    end
  end

  def self.custom_field_values_for_item(item)
    custom_fields = item.collection.custom_fields
    custom_fields.map { |field| item.custom_field_value_for_field(field) }
  end

  def custom_field_value_for_field(field)
    item_custom_field_values.find_by(custom_field_id: field.id)&.value
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  include ImageUploadable

  before_action :set_collection
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_user!, only: [:edit, :update, :destroy]

  # GET /collections/:collection_id/items
  def index
    @items = @collection.items
  end

  # GET /collections/:collection_id/items/1
  def show
    @user = @item.collection.user
    @comments = @item.comments.includes(:user)
    load_custom_fields
  end

  # GET /collections/:collection_id/items/new
  def new
    @item = @collection.items.build
    build_item_custom_field_value
    load_custom_fields
  end

  # POST /collections/:collection_id/items
  def create
    @item = @collection.items.build(item_params.except(:custom_field_values_attributes))
    @item.tags = params[:tags] if params[:tags].present?

    handle_image_upload

    if @item.save
      save_custom_field_values_on_create
      redirect_to [@collection, @item], notice: "Item was successfully created."
    else
      load_custom_fields
      render :new
    end
  end

  # GET /collections/:collection_id/items/1/edit
  def edit
    load_custom_fields
  end

  # PATCH/PUT /collections/:collection_id/items/1
  def update
    handle_image_upload

    @item.tags = params[:tags] if params[:tags].present?

    if @item.update(item_params.except(:custom_field_values_attributes, :image))
      save_custom_field_values_on_update
      redirect_to [@collection, @item], notice: "Item was successfully updated."
    else
      load_custom_fields
      render :edit
    end
  end

  # DELETE /collections/:collection_id/items/1
  def destroy
    @item.destroy
    redirect_to collection_items_path(@collection), notice: "Item was successfully destroyed."
  end

  def like
    # Implement like functionality
  end

  private

  def set_collection
    @collection = Collection.find(params[:collection_id])
  end

  def set_item
    @item = @collection.items.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:name, :description, :image, :tags, custom_field_values_attributes: [:value, :custom_field_id])
  end

  def load_custom_fields
    @custom_fields = @collection.custom_fields
  end

  def build_item_custom_field_value
    @item.item_custom_field_values.build unless @item.item_custom_field_values.any?
  end

  def authorize_user!
    unless current_user == @item.collection.user || current_user.admin?
      redirect_to collection_items_path(@collection), alert: "You are not authorized to perform this action."
    end
  end

  def handle_image_upload
    if params[:item][:image].present?
      encoded_image = Base64.strict_encode64(params[:item][:image].read)
      cloudinary_response = upload_image_to_cloudinary(encoded_image)

      if cloudinary_response && cloudinary_response["secure_url"]
        delete_image_from_cloudinary(@item.image) if action_name == "update" && @item.image.present?
        @item.image = cloudinary_response["secure_url"]
        flash.now[:notice] = "Image uploaded successfully."
      else
        flash.now[:alert] = "Failed to upload image to Cloudinary"
        render action_name == "create" ? :new : :edit
        return
      end
    end
  end

  def save_custom_field_values_on_create
    return unless params[:item][:custom_field_values_attributes].present?

    params[:item][:custom_field_values_attributes].each do |_, value_params|
      @item.item_custom_field_values.create(
        custom_field_id: value_params[:custom_field_id],
        value: value_params[:value],
      )
    end
  end

  def save_custom_field_values_on_update
    if params[:item][:custom_field_values_attributes].present?
      params[:item][:custom_field_values_attributes].each do |_, value_params|
        item_custom_field_value = @item.item_custom_field_values.find_or_initialize_by(
          custom_field_id: value_params[:custom_field_id],
        )
        item_custom_field_value.value = value_params[:value]
        item_custom_field_value.save
      end
    else
      # If no custom field values are provided, create new ones
      load_custom_fields # Load custom fields if not already loaded
      @collection.custom_fields.each do |custom_field|
        @item.item_custom_field_values.build(custom_field: custom_field)
      end
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_comments_section.html.erb
<div class="flex flex-col mt-8 lg:flex-row lg:space-x-8 border-t border-gray-100 dark:border-gray-700">
  <!-- Comments Section -->
  <% if @comments.present? %>
    <div class="w-full lg:w-2/3 bg-white dark:bg-gray-800 py-6 lg:py-16 antialiased">
      <div class="max-w-2xl mx-auto px-4">
        <div class="flex justify-between items-center mb-6">
          <h2 class="text-lg lg:text-2xl font-bold text-gray-900 dark:text-white">Discussion (<%= @item.comments_count %>)</h2>
        </div>
        <% @comments.each do |comment| %>
          <article class="p-6 text-base bg-white rounded-lg dark:bg-gray-900 mb-4">
            <footer class="flex justify-between items-center mb-2">
              <div class="flex items-center">
                <p class="inline-flex items-center mr-3 text-sm text-gray-900 dark:text-white font-semibold">
                  <img class="mr-2 w-6 h-6 rounded-full" src="<%= comment.user.profile_image.present? ?  comment.user.profile_image : asset_path('default_avatar.png') %>" alt="<%= comment.user.username %>">
                  <%= comment.user.username %>
                </p>
                <p class="text-sm text-gray-600 dark:text-gray-400">
                  <time pubdate datetime="<%= comment.created_at.strftime('%Y-%m-%d') %>" title="<%= comment.created_at.strftime('%B %d, %Y') %>"><%= comment.created_at.strftime('%b. %d, %Y') %></time>
                </p>
              </div>
              <% if current_user && (comment.user == current_user || @item.collection.user == current_user || current_user.admin?) %>
                <button id="dropdownComment<%= comment.id %>Button" data-dropdown-toggle="dropdownComment<%= comment.id %>" class="inline-flex items-center p-2 text-sm font-medium text-center text-gray-500 dark:text-gray-400 bg-white rounded-lg hover:bg-gray-100 focus:ring-4 focus:outline-none focus:ring-gray-50 dark:bg-gray-900 dark:hover:bg-gray-700 dark:focus:ring-gray-600" type="button">
                  <svg class="w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 3">
                    <path d="M2 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Zm6.041 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM14 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Z"/>
                  </svg>
                  <span class="sr-only">Comment settings</span>
                </button>
                <!-- Dropdown menu -->
                <div id="dropdownComment<%= comment.id %>" class="hidden z-10 w-36 bg-white rounded divide-y divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600">
                  <ul class="py-1 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownMenuIconHorizontalButton">
                    <li>
                      <%= form_with model: comment, url: collection_item_comment_path(@collection, @item, comment), method: :delete, data: { confirm: "Are you sure you want to delete this comment?" } do |form| %>
                        <%= form.submit "Remove", class: "block py-2 px-4 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white" %>
                      <% end %>
                    </li>
                  </ul>
                </div>
              <% end %>
            </footer>
            <p class="text-gray-500 dark:text-gray-400"><%= comment.content %></p>
          </article>
        <% end %>
      </div>
    </div>
  <% end %>
  <!-- Comment Form Section -->
  <% if user_signed_in? %>
    <div class="w-full lg:w-1/3 bg-white dark:bg-gray-800 py-6 lg:py-16 antialiased">
      <div class="max-w-xl mx-auto px-4">
        <form class="mb-6" action="<%= collection_item_comments_path(@collection, @item) %>" method="post">
          <div class="py-2 px-4 mb-4 bg-white rounded-lg rounded-t-lg border border-gray-200 dark:bg-gray-800 dark:border-gray-700">
            <label for="comment" class="sr-only">Your comment</label>
            <textarea id="comment" name="comment[content]" rows="6" class="px-0 w-full text-sm text-gray-900 border-0 focus:ring-0 focus:outline-none dark:text-white dark:placeholder-gray-400 dark:bg-gray-800" placeholder="Write a comment..." required></textarea>
          </div>
          <button type="submit" class="inline-flex items-center py-2.5 px-4 text-xs font-medium text-center text-white bg-blue-600 rounded-lg focus:ring-4 focus:ring-blue-300 dark:focus:ring-blue-800 hover:bg-blue-700 dark:bg-blue-500 dark:hover:bg-blue-600">
            Post comment
          </button>
        </form>
      </div>
    </div>
  <% else %>
    <p class="text-sm text-gray-500 dark:text-gray-400">You need to <a href="<%= new_user_session_path %>" class="text-blue-600 hover:underline dark:text-blue-500">sign in</a> to post a comment.</p>
  <% end %>
</div>

app/views/items/_item_dropdown.html.erb
<% if current_user && (item.collection.user == current_user || current_user.admin?) %>
  <div class="relative">
    <button id="dropdownButton-<%= item.id %>" data-dropdown-toggle="dropdown-<%= item.id %>" class="inline-block text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:ring-4 focus:outline-none focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-1.5" type="button">
      <span class="sr-only">Open dropdown</span>
      <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 3">
        <path d="M2 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Zm6.041 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM14 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Z"/>
      </svg>
    </button>
    <!-- Dropdown menu -->
    <div id="dropdown-<%= item.id %>" class="z-10 hidden text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 absolute right-0 mt-2">
      <ul class="py-2" aria-labelledby="dropdownButton-<%= item.id %>">
        <li>
          <%= link_to edit_collection_item_path(item.collection, item), class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white" do %>
            Edit
          <% end %>
        </li>
        <li>
          <%= form_with(model: item, url: collection_item_path(item.collection, item), method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: "inline-block") do %>
            <%= submit_tag 'Delete', class: "block px-4 py-2 text-sm text-red-600 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white" %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
<% end %>

app/views/items/_like_button.html.erb
<div class="flex items-center space-x-2">
  <% if current_user && @item.likes.exists?(user_id: current_user.id) %>
    <%= form_with(model: [@collection, @item.likes.build], url: collection_item_like_path(@collection, @item, @item.likes.find_by(user_id: current_user.id)), method: :delete) do |form| %>
      <%= form.button type: "submit", class: "text-red-500 text-xl cursor-pointer" do %>
        <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 512 512" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg">
          <path fill="currentColor" d="M462.3 62.6C407.5 15.9 326 24.3 275.7 76.2L256 96.5l-19.7-20.3C186.1 24.3 104.5 15.9 49.7 62.6c-62.8 53.6-66.1 149.8-9.9 207.9l193.5 199.8c12.5 12.9 32.8 12.9 45.3 0l193.5-199.8c56.3-58.1 53-154.3-9.8-207.9z"></path>
        </svg>
      <% end %>
    <% end %>
  <% else %>
    <%= form_with(model: [@collection, @item.likes.build], url: collection_item_likes_path(@collection, @item), method: :post) do |form| %>
      <%= form.button type: "submit", class: "text-red-500 text-xl cursor-pointer" do %>
        <svg stroke="currentColor" fill="currentColor" stroke-width="0" viewBox="0 0 512 512" height="1em" width="1em" xmlns="http://www.w3.org/2000/svg">
          <path d="M458.4 64.3C400.6 15.7 311.3 23 256 79.3 200.7 23 111.4 15.6 53.6 64.3-21.6 127.6-10.6 230.8 43 285.5l175.4 178.7c10 10.2 23.4 15.9 37.6 15.9 14.3 0 27.6-5.6 37.6-15.8L469 285.6c53.5-54.7 64.7-157.9-10.6-221.3zm-23.6 187.5L259.4 430.5c-2.4 2.4-4.4 2.4-6.8 0L77.2 251.8c-36.5-37.2-43.9-107.6 7.3-150.7 38.9-32.7 98.9-27.8 136.5 10.5l35 35.7 35-35.7c37.8-38.5 97.8-43.2 136.5-10.6 51.1 43.1 43.5 113.9 7.3 150.8z"></path>
        </svg>
      <% end %>
    <% end %>
  <% end %>
  <span class="likes-count text-gray-500 mb-2"><%= @item.likes_count %></span>
</div>

app/views/items/_tag_input.html.erb
<div class="mb-4" data-controller="tags" data-tags-target="container" data-tags="<%= @item.tags.join(',') %>">
  <!-- Label for showing tags -->
  <label for="tags" class="block text-sm font-medium text-gray-700 dark:text-gray-200 mb-2">Show Tags:</label>
  <!-- Selected tags will appear here -->
  <div data-tags-target="tags" class="my-2">
    <!-- This section will display selected tags -->
    <%= hidden_field_tag 'tags', @item.tags.join(','), data: { target: 'tags.tagsInput' } %>
  </div>
  <!-- Input field for adding new tags -->
  <input data-tags-target="input" data-action="keypress->tags#addTag" type="text" class="form-input block w-full px-4 py-2 text-sm border-gray-300 rounded-md focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-500 dark:focus:ring-blue-600 dark:focus:border-blue-600" placeholder="Enter custom tag and press enter" />
  <!-- Dropdown menu for selecting recommended tags -->
  <div class="relative inline-block mt-2">
    <button id="dropdownTagButton" data-dropdown-toggle="dropdownTag" class="inline-flex items-center px-4 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" type="button">Recommended Tags<svg class="w-2.5 h-2.5 ms-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/></svg></button>
    <!-- Dropdown menu for recommended tags -->
    <div id="dropdownTag" class="z-10 hidden bg-white rounded-lg shadow w-60 dark:bg-gray-700 overflow-y-auto" style="max-height: 12rem;">
      <ul class="px-3 pb-3 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownTagButton">
        <% Tag.all.each do |tag| %>
          <li>
            <div class="flex items-center p-2 rounded hover:bg-gray-100 dark:hover:bg-gray-600">
              <%= check_box_tag "", tag.name, @item.tags.include?(tag.name), data: { action: 'change->tags#toggleTag', tag_name: tag.name, selected: @item.tags.include?(tag.name) }, id: "checkbox-item-#{tag.id}", class: 'w-4 h-4 text-blue-600 bg-gray-100 border-gray-300 rounded focus:ring-blue-500 dark:focus:ring-blue-600 dark:ring-offset-gray-700 dark:focus:ring-offset-gray-700 focus:ring-2 dark:bg-gray-600 dark:border-gray-500' %>
              <label for="checkbox-item-<%= tag.id %>" class="w-full ms-2 text-sm font-medium text-gray-900 rounded dark:text-gray-300"><%= tag.name %></label>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <!-- Container for hidden inputs representing selected tags -->
  <div class="tag-inputs">
    <!-- Hidden inputs for tags[] will be appended here -->
  </div>
</div>

app/views/items/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Items#create</h1>
  <p>Find me in app/views/items/create.html.erb</p>
</div>

app/views/items/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">Items#destroy</h1>
  <p>Find me in app/views/items/destroy.html.erb</p>
</div>

app/views/items/index.html.erb
<div class="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-md hover:shadow-lg transition-shadow duration-300">
  <div class="flex justify-between items-center mb-4">
    <h2 class="text-2xl font-semibold text-gray-900 dark:text-gray-100">Items List</h2>
    <%= link_to 'Go to Collection', collection_path(@collection), class: 'inline-flex items-center py-2 px-4 text-sm font-medium text-white bg-blue-600 rounded-lg hover:bg-blue-700 focus:ring-4 focus:ring-blue-300 dark:focus:ring-blue-800' %>
  </div>
  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
    <%= render partial: 'shared/item', locals: { items: @items} %>
  </div>
</div>

app/views/items/show.html.erb
<div class="bg-white p-6 w-full rounded-lg shadow-md hover:shadow-lg transition-shadow duration-300 dark:bg-gray-800">
  <div class="flex flex-col md:flex-row">
    <div class="md:w-1/3 w-full mb-4 md:mb-0 md:mr-4">
      <div class="relative w-full aspect-w-1 aspect-h-1">
        <img src="<%= @item.image? ? @item.image : asset_path('default_item_img.jpg') %>" alt="<%= @item.name %>" class="absolute top-0 left-0 w-full h-full object-cover rounded-md">
      </div>
    </div>
    <div class="md:w-2/3 w-full">
      <div class="flex justify-between items-center mb-2">
        <h3 class="text-2xl font-semibold text-gray-900 dark:text-gray-100 mb-2">
          <%= @item.name %>
        </h3>
        <% if current_user && (@item.collection.user == current_user || current_user.admin?) %>
          <div class="relative">
            <button id="dropdownButton-<%= @item.id %>" data-dropdown-toggle="dropdown-<%= @item.id %>" class="inline-block text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:ring-4 focus:outline-none focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-1.5" type="button">
              <span class="sr-only">Open dropdown</span>
              <svg class="w-5 h-5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 16 3">
                <path d="M2 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Zm6.041 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM14 0a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3Z"/>
              </svg>
            </button>
            <!-- Dropdown menu -->
            <div id="dropdown-<%= @item.id %>" class="z-10 hidden text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700 absolute right-0 mt-2">
              <ul class="py-2" aria-labelledby="dropdownButton-<%= @item.id %>">
                <li>
                  <%= link_to edit_collection_item_path(@item.collection, @item), class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white" do %>
                    Edit
                  <% end %>
                </li>
                <li>
                  <%= form_with(model: @item, url: collection_item_path(@item.collection, @item), method: :delete, data: { turbo_confirm: 'Are you sure?' }, class: "inline-block") do %>
                    <%= submit_tag 'Delete', class: "block px-4 py-2 text-sm text-red-600 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white" %>
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
        <% end %>
      </div>
      <p class="text-sm text-gray-600 dark:text-gray-400 mb-4"><%= @item.description %></p>
      <ul class="text-sm text-gray-600 dark:text-gray-400 mb-4">
        <% @custom_fields.each do |custom_field| %>
          <% custom_field_value = @item.item_custom_field_values.find_by(custom_field_id: custom_field.id) %>
          <li><strong><%= custom_field.label %>:</strong> <%= custom_field_value.value if custom_field_value %></li>
        <% end %>
      </ul>
      <% if @item.tags.any? %>
        <div class="flex flex-wrap mb-4">
          <h4 class="text-lg font-semibold text-gray-900 dark:text-gray-100 mr-2">Tags:</h4>
          <% @item.tags.each do |tag| %>
            <span class="bg-gray-200 dark:bg-gray-700 px-2 py-1 dark:text-gray-300 rounded text-sm mr-2 mb-2"><%= tag %></span>
          <% end %>
        </div>
      <% end %>
      <p class="text-sm text-gray-500 dark:text-gray-300 mb-2">
        Collection: <%= link_to @item.collection.name, collection_path(@item.collection), class: "text-blue-500 hover:underline" %>
      </p>
      <% if user_signed_in? %>
        <p class="text-xs text-gray-500 dark:text-gray-300">
          Added by <%= link_to @item.collection.user.username, user_profile_path(@item.collection.user), class: "text-blue-500 hover:underline" %>
        </p>
      <% end %>
      <p class="text-xs text-gray-500 dark:text-gray-300 mb-4">
        <%= @item.created_at.strftime("%d.%m.%Y at %H:%M:%S") %>
      </p>
      <%= render 'like_button' %>
    </div>
  </div>
  <%= render 'comments_section' %>
</div>

app/views/items/update.html.erb
<div>
  <h1 class="font-bold text-4xl">Items#update</h1>
  <p>Find me in app/views/items/update.html.erb</p>
</div>